[package]
name = "digidist"
version = "0.1.0"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]

[dependencies]
vst2 = "0.0.1"
num = "0.2.0"
rustfft = "3.0.0"
num-traits = "0.2.8"
math = "0.0.2"

[lib]
crate-type = ["dylib"]